title: Jolly Minou FC
description: Where Passion Meets Performance.
baseurl: ""
url: https://www.jollyminoufc.vom

#theme: cvless

# site settings
taglong: Where Passion Meets Performance.
tagshort: Jekyll theme

# author settings
author:
  name: Place Holder
  email: username@domain.com
photo: assets/files/photo.jpg
address: Foobar Hall 1.23
phone: +1 234 567 890

# social media links
social:
  #facebook: username
  #github: username
  #instagram: username
  #linkedin: username
  #stackoverflow: 0000000/username
  x: jollyminoufc

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
